---
title: "Team 5 - Data 624 - Project 2"
author: "Ohannes (Hovig) Ohannessian, Niteen Kumar, Gurpreet Singh, Peter Goodridge"
date: "4/20/2019"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE, Load_packages}
library("readxl")
library(httr)
library(caret)
library(tidyverse)
library(kableExtra)
library(caretEnsemble)
library(mice)
library(kableExtra)
library(parallel)
library(doParallel)
library(ggplot2)
library(Hmisc)
library(psych)
library(reshape2)
```


```{r}
student_evaluation_gh_file <- "https://github.com/hovig/Team5-Data624-Project2/raw/master/StudentEvaluation.xlsx"
student_data_gh_file <- "https://github.com/hovig/Team5-Data624-Project2/raw/master/StudentData.xlsx"

se_temp_file <- tempfile(fileext = ".xlsx")
sd_temp_file <- tempfile(fileext = ".xlsx")

se_data <- GET(student_evaluation_gh_file, authenticate(Sys.getenv("GITHUB_PAT"), ""), write_disk(path = se_temp_file))
df_data <- GET(student_data_gh_file, authenticate(Sys.getenv("GITHUB_PAT"), ""), write_disk(path = sd_temp_file))

se_data <- readxl::read_excel(se_temp_file)
sd_data <- readxl::read_excel(sd_temp_file)

```

```{r}
hist.data.frame(se_data)
```


```{r}
hist.data.frame(sd_data)
```


####Process Data

```{r}
show_results <- function(model){ 
  rslts <- model$results %>%
    arrange(RMSE)
  head(rslts, 10) %>% kable () %>% kable_styling(bootstrap_options = "striped", full_width = F)
}
bev_raw <- read_csv('https://raw.githubusercontent.com/hovig/Team5-Data624-Project2/master/StudentData.csv') %>%
drop_na(PH)
```

```{r}
dim(bev_raw)
str(bev_raw)
hist.data.frame(bev_raw)
table(bev_raw$`Brand Code`)
summary(bev_raw)
describe(bev_raw %>% select(-`Brand Code`))
```


#### Zero variance

```{r}
df1 <- bev_raw %>% select(-`Brand Code`) %>% mutate_each(funs(as.numeric(.)))%>%complete.cases()%>%
       as.data.frame()


names(df1)[nearZeroVar(df1)]
nzv <- nearZeroVar(bev_raw,saveMetrics= TRUE)
nzv[nzv$nzv,]
```


#### Box plot

```{r}
df.m <- melt(bev_raw %>% select(-MFR, -`Filler Speed`, -`Carb Flow`,-`Bowl Setpoint`,`Carb Pressure1`,
            `Hyd Pressure4`, `Air Pressurer`, `Carb Temp`, `Filler Level`, `Mnf Flow`), id.var = "Brand Code")
p <-ggplot(data = df.m, aes(x=variable, y=value)) + 
  geom_boxplot(outlier.colour="red", outlier.shape=8, outlier.size=4,aes(fill=variable)) +     
  scale_y_continuous(name = "Predictors for PH", breaks = seq(0, 2, 0.5))  + 
  coord_flip()
p
```

### Normality 

```{r}
bev_raw%>%
 select(-`Brand Code`) %>%   
  select(2:20) %>%         
  gather() %>%                            
  ggplot(aes(value)) +                     
    facet_wrap(~ key, scales = "free") +  
    geom_density()  
bev_raw%>%
 select(-`Brand Code`) %>%   
  select(`Carb Flow`, Density, MFR, Balling, `Pressure Vacuum`, PH, `Oxygen Filler`, `Bowl Setpoint`, `Pressure Setpoint`, `Air Pressurer`, `Alch Rel`,`Carb Rel`,`Balling Lvl`)   %>%               
  gather() %>%                             
  ggplot(aes(value)) +                     
    facet_wrap(~ key, scales = "free") +  
    geom_density() 
```



```{r}
bev <- select(bev_raw, -PH)
cols <- str_replace(colnames(bev), '\\s', '')
colnames(bev) <- cols
bev <- mutate(bev, BrandCode = ifelse(is.na(BrandCode), 'Unknown', BrandCode))
y <- bev_raw$PH

zero_vars <- nearZeroVar(bev)
bev_new <- bev[, -zero_vars]

pred <- mice(data = bev_new, m = 5, method = 'rf', maxit = 3)
bev_imputed <- complete(pred)

form <- dummyVars(~ ., data = bev_imputed)
bev_imputed <- predict(form, bev_imputed) %>% data.frame() %>% as.matrix()
str(bev_imputed)

write.csv(bev_imputed, file = "predictions.csv")
```

####Build Models

These models only went through basic tuning.  We can tune invididually and add to the model list

```{r}
xgb_grid <- expand.grid(eta = c(.025, .05), nrounds = c(750,1000), max_depth = c(3,5,7,9), gamma = c(0),
                          colsample_bytree = c(.6),
                          min_child_weight = c(.6,1),
                          subsample = c(.6))
cub_grid <- expand.grid(.committees = c(1,3,5), .neighbors = c(1,3,5,7,9))
svm_grid <- expand.grid(.C = c(.5,1,2,4,8,16,32,64,128), .sigma = c(.005,.01,.5, .1))
mars_grid <- expand.grid(.degree = c(1,2), .nprune = seq(16,36,4))
dart_grid <- expand.grid(eta = c(.025), nrounds = c(1000), gamma = c(.1), skip_drop = c(.2,.6), rate_drop = c(.2,.6), max_depth = c(5),
                          colsample_bytree = c(.6),
                          min_child_weight = c(.6),
                          subsample = c(.6))

tuning_list <-list(
  xgbt = caretModelSpec(method="xgbTree", tuneGrid = xgb_grid),
  xgbd = caretModelSpec(method="xgbDART", tuneGrid = dart_grid),
  cub = caretModelSpec(method="cubist", tuneGrid = cub_grid),
  svm = caretModelSpec(method="svmRadial", tuneGrid = svm_grid),
  mars = caretModelSpec(method="bagEarth", tuneGrid = mars_grid)
)

cl <- makeCluster(detectCores())
registerDoParallel(cl)
set.seed(42)
my_control <- trainControl(method = 'cv',
                           number = 5,
                           savePredictions = 'final',
                           index = createFolds(y, 5),
                           allowParallel = TRUE) 
```

####Test Stack

```{r message=FALSE, warning=FALSE}
mod_list <- caretList(
  x = bev_imputed,
  y = y,
  preProcess = c('center', 'scale'),
  trControl = my_control,
  tuneList = tuning_list
)

show_results(mod_list$xgbt)
show_results(mod_list$xgbd)
show_results(mod_list$cub)
show_results(mod_list$svm)
show_results(mod_list$mars)

resamples <- resamples(mod_list)
modelCor(resamples)
```


```{r}
ensemble1 <- caretStack(
  mod_list,
  method="glm",
  metric="RMSE",
  trControl=trainControl(
    method="cv",
    number=5,
    savePredictions="final"
  )
)
ensemble1
```

```{r}
ensemble2 <- caretEnsemble(mod_list, 
                        metric = 'RMSE', 
                        trControl=trainControl(
                          method="cv",
                          number=5,
                          savePredictions="final"
                        ))
ensemble2
stopCluster(cl)
```

